[package]
name = "postgres-vs"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.4"
async-std = "1.10.0"
tokio = { version = "1.13.0", features = ["full"] }
tokio-postgres = { version = "0.7.5", features = ["with-serde_json-1"] }
