name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install PostgreSQL
      run: sudo apt install postgresql postgresql-contrib
    - uses: actions/checkout@v2
    - name: Start Postgres
      run: |
        sudo -i -u postgres
        postgresql
        psql
    - name: Build & Run
      run: cargo run
