name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: harmon758/postgresql-action@v1
      with:
        postgresql version: '11'
    - uses: actions/checkout@v2
    - name: Start Postgres
      run: |
        createuser postgres
        createdb postgres
        su - postgres
        psql
    - name: Build & Run
      run: cargo run --verbose
