name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install PostgreSQL
      run: sudo apt install postgresql postgresql-contrib postgresql-common
    - uses: actions/checkout@v2
    - name: Start Postgres
      run: |
        cd ~
        PATH=$PATH:/usr/lib/postgresql/12/bin
        export PATH
        mkdir _data
        initdb _data
        sudo -i -u postgres
        sudo psql -U postgres -W
    - name: Build & Run
      run: cargo run
