name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: harmon758/postgresql-action@v1
      with:
        postgresql version: '11'
    - uses: actions/checkout@v2
    - name: Start Postgres
      run: |
        psql postgres://postgres:@localhost:5432/postgres << SQL

        CREATE TABLE links (id bigserial PRIMARY KEY, from_id bigint DEFAULT 0, to_id bigint DEFAULT 0);

        CREATE INDEX IF NOT EXISTS links__id_hash ON ${TABLE_NAME} USING hash (id);
        CREATE INDEX IF NOT EXISTS links__from_id_hash ON ${TABLE_NAME} USING hash (from_id);
        CREATE INDEX IF NOT EXISTS links__from_id_btree ON ${TABLE_NAME} USING btree (from_id);
        CREATE INDEX IF NOT EXISTS links__to_id_hash ON ${TABLE_NAME} USING hash (to_id);
        CREATE INDEX IF NOT EXISTS links__to_id_btree ON ${TABLE_NAME} USING btree (to_id);

        SQL
    - name: Build & Run
      run: cargo run
